// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package user

import (
	"net/http"

	"github.com/MrLeeang/my-zero/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/ping",
				Handler: pingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user",
				Handler: pingHandler(serverCtx),
			},
		},
	)
}
