// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package login

import (
	"net/http"

	"github.com/MrLeeang/my-zero/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext, prefix string) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/login/ping",
				Handler: pingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: loginHandler(serverCtx),
			},
		},
		rest.WithPrefix(prefix),
	)
}
