Name: ping
Host: 127.0.0.1
Port: 8888
Log:
  Encoding: json
#链路追踪
Telemetry:
  Name: user-api
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger
JwtAuth:
  AccessSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  AccessExpire: 604800
DevServer:
    Enabled: true
LoginSvc:
  Etcd:
    Hosts:
    - 192.168.2.235:2379
    Key: loginsvc.rpc
UserSvc:
  Etcd:
    Hosts:
    - 192.168.2.235:2379
    Key: usersvc.rpc