// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: usersvc.proto

package server

import (
	"context"

	"github.com/MrLeeang/my-zero/usersvc/internal/logic"
	"github.com/MrLeeang/my-zero/usersvc/internal/svc"
	"github.com/MrLeeang/my-zero/usersvc/usersvc"
)

type UsersvcServer struct {
	svcCtx *svc.ServiceContext
	usersvc.UnimplementedUsersvcServer
}

func NewUsersvcServer(svcCtx *svc.ServiceContext) *UsersvcServer {
	return &UsersvcServer{
		svcCtx: svcCtx,
	}
}

func (s *UsersvcServer) Ping(ctx context.Context, in *usersvc.Request) (*usersvc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
