// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.17.3
// source: loginsvc.proto

package loginsvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Loginsvc_Ping_FullMethodName  = "/loginsvc.Loginsvc/Ping"
	Loginsvc_Login_FullMethodName = "/loginsvc.Loginsvc/Login"
)

// LoginsvcClient is the client API for Loginsvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginsvcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
}

type loginsvcClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginsvcClient(cc grpc.ClientConnInterface) LoginsvcClient {
	return &loginsvcClient{cc}
}

func (c *loginsvcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Loginsvc_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginsvcClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, Loginsvc_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginsvcServer is the server API for Loginsvc service.
// All implementations must embed UnimplementedLoginsvcServer
// for forward compatibility.
type LoginsvcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	Login(context.Context, *LoginReq) (*LoginResp, error)
	mustEmbedUnimplementedLoginsvcServer()
}

// UnimplementedLoginsvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginsvcServer struct{}

func (UnimplementedLoginsvcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLoginsvcServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedLoginsvcServer) mustEmbedUnimplementedLoginsvcServer() {}
func (UnimplementedLoginsvcServer) testEmbeddedByValue()                  {}

// UnsafeLoginsvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginsvcServer will
// result in compilation errors.
type UnsafeLoginsvcServer interface {
	mustEmbedUnimplementedLoginsvcServer()
}

func RegisterLoginsvcServer(s grpc.ServiceRegistrar, srv LoginsvcServer) {
	// If the following call pancis, it indicates UnimplementedLoginsvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Loginsvc_ServiceDesc, srv)
}

func _Loginsvc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginsvcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Loginsvc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginsvcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Loginsvc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginsvcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Loginsvc_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginsvcServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Loginsvc_ServiceDesc is the grpc.ServiceDesc for Loginsvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Loginsvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loginsvc.Loginsvc",
	HandlerType: (*LoginsvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Loginsvc_Ping_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Loginsvc_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loginsvc.proto",
}
