// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: loginsvc.proto

package server

import (
	"context"

	"github.com/MrLeeang/my-zero/loginsvc/internal/logic"
	"github.com/MrLeeang/my-zero/loginsvc/internal/svc"
	"github.com/MrLeeang/my-zero/loginsvc/loginsvc"
)

type LoginsvcServer struct {
	svcCtx *svc.ServiceContext
	loginsvc.UnimplementedLoginsvcServer
}

func NewLoginsvcServer(svcCtx *svc.ServiceContext) *LoginsvcServer {
	return &LoginsvcServer{
		svcCtx: svcCtx,
	}
}

func (s *LoginsvcServer) Ping(ctx context.Context, in *loginsvc.Request) (*loginsvc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *LoginsvcServer) Login(ctx context.Context, in *loginsvc.LoginReq) (*loginsvc.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}